taxonomy: topic
_id: security
name: Security
shortname: Security
parent: Azure
keywords:
  - security
  - key vault
  - azure information protection
  - azure ddos protection
  - security center
hashtags:
  - "#security"
images:
  - https://everyday-cc.github.io/azure/assets/images/topics/security.jpg
services:
  news: https://everyday-cc.github.io/azure/api/news/security/
  learning: https://everyday-cc.github.io/azure/api/learning/security/
